site_name: Quantum Optics Group at LKB
nav:
  - Home: index.md
  - About: about.md
  - User Guide:
    - Writing your docs: writing-your-docs.md
    - Styling your docs: styling-your-docs.md
theme:
  name: material
plugins:
  - mkdocs-jupyter